
name = "DashChemicalFlow"
uuid = "1b08a953-4be3-4667-9a23-9ee86fd4f688"
authors = ["liupeng.dalian@gmail.com <liupeng.dalian@gmail.com>"]
version = "0.1.8"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
